array: [
  {
    name: "'Y' Junction Udhana Magdalla Road BRTS",
    lat: 21.146092,
    lng: 72.760957,
    details:
      "'Y' Junction Udhana Magdalla Road BRTS, Vesu, Rundh, Surat, Gujarat 394518, India",
    timetable: [
      { bus_number: "12", destination: "Sarthana Nature Park BRTS" },
      { bus_number: "12", destination: "ONGC Colony" },
    ],
  },
  {
    name: "'Y' Junction Dumas Road BRTS",
    lat: 21.144231,
    lng: 72.757999,
    details: "'Y' Junction Dumas Road BRTS, Vesu, Surat, Gujarat 394518, India",
    timetable: [
      { bus_number: "216K", destination: "Chowk" },
      { bus_number: "12", destination: "Sarthana Nature Park BRTS" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "14", destination: "ONGC Colony" },
      { bus_number: "136", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Maharana Pratap Junction BRTS",
    lat: 21.148379,
    lng: 72.766442,
    details:
      "Maharana Pratap Junction BRTS, Vesu, Rundh, Surat, Gujarat 394518, India",
    timetable: [
      { bus_number: "12", destination: "Sarthana Nature Park BRTS" },
      { bus_number: "12", destination: "ONGC Colony" },
    ],
  },
  {
    name: "Magdalla T Junction BRTS",
    lat: 21.147673,
    lng: 72.760584,
    details:
      "Magdalla T Junction BRTS, Piplod, Rundh, Surat, Gujarat 394518, India",
    timetable: [
      { bus_number: "14", destination: "Kosad EWS H2" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "14", destination: "ONGC Colony" },
      { bus_number: "216B", destination: "Chowk" },
      { bus_number: "216K", destination: "Chowk" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "206", destination: "Chowk" },
    ],
  },
  {
    name: "Jolly Residency",
    lat: 21.146242,
    lng: 72.768395,
    details: "Jolly Residency, Vesu, Rundh, Surat, Gujarat 394518, India",
    timetable: [
      { bus_number: "106R", destination: "Railway Station Terminal" },
      { bus_number: "106R", destination: "Abhva Gaam" },
    ],
  },
  {
    name: "S.D Planets School",
    lat: 21.152731,
    lng: 72.771855,
    details: "S.D Planets School, Piplod, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "106R", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "S.D. Jain School BRTS",
    lat: 21.151883,
    lng: 72.772,
    details: "S.D. Jain School BRTS, Piplod, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "706", destination: "Iskcon Circle" },
      { bus_number: "12", destination: "ONGC Colony" },
      { bus_number: "12", destination: "Sarthana Nature Park BRTS" },
      { bus_number: "106R", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "J.H. Ambani School BRTS",
    lat: 21.152066,
    lng: 72.775294,
    details: "J.H. Ambani School BRTS, Vesu, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "706", destination: "V.N.S.G. University" },
      { bus_number: "12", destination: "Sarthana Nature Park BRTS" },
      { bus_number: "706", destination: "Iskcon Circle" },
    ],
  },
  {
    name: "Someshwar Junction BRTS",
    lat: 21.153747,
    lng: 72.779741,
    details: "Someshwar Junction BRTS, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "706", destination: "Iskcon Circle" },
      { bus_number: "12", destination: "Sarthana Nature Park BRTS" },
      { bus_number: "15AA", destination: "Althan Depot/Terminal" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "15CC", destination: "Althan Depot/Terminal" },
      { bus_number: "706", destination: "V.N.S.G. University" },
      { bus_number: "126R", destination: "Railway Station Terminal" },
      { bus_number: "506", destination: "Sunrise Vidyalaya Dindoli" },
    ],
  },
  {
    name: "Piplod Main Road",
    lat: 21.154327,
    lng: 72.779231,
    details:
      "Piplod Main Road, Sarunagar, Piplod, Surat, Gujarat 395007, India",
    timetable: [],
  },
  {
    name: "K.P Commerce College",
    lat: 21.183411,
    lng: 72.808864,
    details: "K.P Commerce College, Athwa Gate, Surat, Gujarat 395001, India",
    timetable: [{ bus_number: "106R", destination: "Abhva Gaam" }],
  },
  {
    name: "Police Commissioner Office",
    lat: 21.182311,
    lng: 72.803757,
    details:
      "Police Commissioner Office, Chopati, Police Line, Athwa, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "206", destination: "Chowk" },
      { bus_number: "216B", destination: "Bhimpore" },
      { bus_number: "153R", destination: "Kapodara" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "706", destination: "ISKCON Circle" },
    ],
  },
  {
    name: "City Civic Centre",
    lat: 21.18039,
    lng: 72.801418,
    details:
      "City Civic Centre, Navo Mohollow, Meghdoot Society, Athwalines, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "226J", destination: "V.N.S.G. University" },
      { bus_number: "716", destination: "Sai Pujan Residency" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "716", destination: "Gail India Ltd VIP Road U" },
      { bus_number: "706", destination: "ISKCON Circle" },
    ],
  },
  {
    name: "Gandhi College",
    lat: 21.181611,
    lng: 72.815645,
    details: "Gandhi College, Majura Gate, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "106R", destination: "Railway Station Terminal" },
      { bus_number: "01", destination: "Vanita Vishram Ground" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "106S", destination: "Abhva Gam" },
      { bus_number: "205G", destination: "Gabheni Gam" },
      { bus_number: "02", destination: "Majura Gate1" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "117", destination: "Suman Jyot EWS" },
      { bus_number: "136", destination: "Surat Airport" },
    ],
  },
  {
    name: "Mahavir Hospital",
    lat: 21.184932,
    lng: 72.814035,
    details:
      "Mahavir Hospital, Opp. Gandhi Smruti Bhavan, Nanpura, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "205G", destination: "Gabheni Gaam" },
      { bus_number: "205S", destination: "Sachin Railway Station" },
      { bus_number: "205K", destination: "Lajpore Jail" },
      { bus_number: "205K", destination: "Chowk" },
    ],
  },
  {
    name: "Girls Polytechnic",
    lat: 21.186793,
    lng: 72.810452,
    details:
      "Girls Polytechnic, Kharwawad, Nanpura, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "216B", destination: "Bhimpore" },
      { bus_number: "226J", destination: "Kosad Gaam" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "206", destination: "C.K. Pithwala Eng. College" },
      { bus_number: "226J", destination: "V.N.S.G. University" },
    ],
  },
  {
    name: "Athvagate",
    lat: 21.185972,
    lng: 72.810066,
    details: "Athvagate, Athwa Gate, Surat, Gujarat 395001, India",
    timetable: [],
  },
  {
    name: "Athwagate",
    lat: 21.185152,
    lng: 72.811332,
    details:
      "Athwagate, Near Kalyan Apartment, Athwa Gate, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "106S", destination: "Abhva Gaam" },
      { bus_number: "02", destination: "Vanita Vishram Ground" },
      { bus_number: "117", destination: "Suman Jyot EWS" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "153R", destination: "Kapodara" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "706", destination: "Iskcon Circle" },
    ],
  },
  {
    name: "Man Mandir Apartment",
    lat: 21.187713,
    lng: 72.814851,
    details:
      "Man Mandir Apartment, Timaliawad, Nanpura, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "205G", destination: "Gabheni Gaam" },
      { bus_number: "205S", destination: "Sachin Railway Station" },
      { bus_number: "205K", destination: "Lajpore Jail" },
      { bus_number: "205K", destination: "Chowk" },
    ],
  },
  {
    name: "Nanpura Post Office",
    lat: 21.190254,
    lng: 72.812963,
    details: "Nanpura Post Office, Nanpura, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "216B", destination: "Bhimpore" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "206", destination: "C.K. Pithwala Eng. College" },
      { bus_number: "226J", destination: "V.N.S.G. University" },
    ],
  },
  {
    name: "Bahumali",
    lat: 21.188453,
    lng: 72.810924,
    details: "Bahumali, Kharwawad, Nanpura, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "216B", destination: "Bhimpore" },
      { bus_number: "226J", destination: "Kosad Gaam" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "206", destination: "C.K. Pithwala Eng. College" },
      { bus_number: "226J", destination: "V.N.S.G. University" },
    ],
  },
  {
    name: "Kuvawadi",
    lat: 21.189654,
    lng: 72.817082,
    details: "Kuvawadi, Timaliawad, Nanpura, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "205G", destination: "Gabheni Gaam" },
      { bus_number: "205S", destination: "Sachin Railway Station" },
      { bus_number: "205K", destination: "Lajpore Jail" },
      { bus_number: "205K", destination: "Chowk" },
    ],
  },
  {
    name: "Machhiwad",
    lat: 21.191814,
    lng: 72.817168,
    details: "Machhiwad, Machhiwar, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "205G", destination: "Gabheni Gaam" },
      { bus_number: "205S", destination: "Sachin Railway Station" },
      { bus_number: "204", destination: "Raj Empire Godadara" },
      { bus_number: "209J", destination: "Vrukshlaxmi Society" },
      { bus_number: "205K", destination: "Lajpore Jail" },
      { bus_number: "205K", destination: "Chowk" },
    ],
  },
  {
    name: "BAPS Swaminarayan Sanstha",
    lat: 21.192635,
    lng: 72.807362,
    details:
      "BAPS Swaminarayan Sanstha, Anand Vatika Society, Bapu Nagar, Adajan, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "147J", destination: "Lambe Hanuman Temple" },
      { bus_number: "147J", destination: "Green City Bhatha" },
    ],
  },
  {
    name: "Corporation School",
    lat: 21.195275,
    lng: 72.809615,
    details:
      "Corporation School, Bapu Nagar, Adajan, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "147J", destination: "Lambe Hanuman Temple" },
      { bus_number: "147J", destination: "Green City Bhatha" },
    ],
  },
  {
    name: "Shakti Niketan Mandir",
    lat: 21.196076,
    lng: 72.807105,
    details:
      "Shakti Niketan Mandir, Jai Ambe Society, Adajan, Surat, Gujarat 395009, India",
    timetable: [],
  },
  {
    name: "Spipa (Surat)",
    lat: 21.194635,
    lng: 72.793629,
    details:
      "Spipa (Surat), Shri Nath Society ,Adajan Gam, Adajan Gam, Adajan, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "117", destination: "Suman Jyot EWS" },
      { bus_number: "117P", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Shahi Masjid Adajan Gam",
    lat: 21.191174,
    lng: 72.794209,
    details:
      "Shahi Masjid Adajan Gam, Adajan Gam, Adajan, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "117", destination: "Suman Jyot EWS" },
      { bus_number: "117P", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Van Bhavan",
    lat: 21.195155,
    lng: 72.793168,
    details:
      "Van Bhavan, Shri Nath Society ,Adajan Gam, Adajan Gam, Adajan, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "107", destination: "Vivekanand College" },
      { bus_number: "107J", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Shanti Kunj",
    lat: 21.194795,
    lng: 72.790486,
    details:
      "Shanti Kunj, Hariom Nagar Society,Adajan Gam, Adajan Gam, Adajan, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "107", destination: "Vivekanand College" },
      { bus_number: "107J", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Green Avenue",
    lat: 21.194375,
    lng: 72.786183,
    details:
      "Green Avenue, TGB, Adajan Gam, Adajan, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "107J", destination: "Vivekanand College" },
      { bus_number: "107J", destination: "Railway Station Terminal" },
      { bus_number: "716", destination: "Gail India Ltd VIP Road Vesu" },
    ],
  },
  {
    name: "Pal Gaam",
    lat: 21.193525,
    lng: 72.779896,
    details: "Pal Gaam, Adajan Gam, Surat, Gujarat 395009, India",
    timetable: [],
  },
  {
    name: "Trinity Business Park",
    lat: 21.190874,
    lng: 72.788683,
    details:
      "Trinity Business Park, Adajan Gam, Adajan, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "147J", destination: "Lambe Hanuman Temple" },
      { bus_number: "716", destination: "Sai Pujan Residency" },
      { bus_number: "716", destination: "Gail India Ltd VIP Road Vesu" },
    ],
  },
  {
    name: "SMC Party Plot Pal",
    lat: 21.190244,
    lng: 72.782149,
    details: "SMC Party Plot Pal, Adajan Gam, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "147J", destination: "Green City Bhatha" },
      { bus_number: "147J", destination: "Lambe Hanuman Temple" },
    ],
  },
  {
    name: "Saurabh Society",
    lat: 21.190474,
    lng: 72.785422,
    details:
      "Saurabh Society, Adajan Gam, Adajan, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "147J", destination: "Green City Bhatha" },
      { bus_number: "147J", destination: "Lambe Hanuman Temple" },
    ],
  },
  {
    name: "Sargam Shopping Centre",
    lat: 21.171506,
    lng: 72.790722,
    details:
      "Sargam Shopping Centre, City Light Town, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "206", destination: "C.K. Pithawala Eng. College" },
    ],
  },
  {
    name: "Shrungar Society City Light Road",
    lat: 21.172507,
    lng: 72.793554,
    details:
      "Shrungar Society City Light Road, Shringar Society, City Light Town, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "706", destination: "Iskcon Circle" },
      { bus_number: "126R", destination: "Railway Station Terminal" },
      { bus_number: "126R", destination: "Someshwar Junction" },
      { bus_number: "706", destination: "V.N.S.G. University" },
    ],
  },
  {
    name: "Sushrut Hospital",
    lat: 21.16948,
    lng: 72.787578,
    details:
      "Sushrut Hospital, SVNIT Campus, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "226J", destination: "V.N.S.G. University" },
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "107J", destination: "Railway Station Terminal" },
      { bus_number: "206", destination: "Chowk" },
      { bus_number: "206", destination: "C.K. Pithawala Eng. College" },
      { bus_number: "136", destination: "Surat Airport" },
    ],
  },
  {
    name: "Umra Food Park",
    lat: 21.168665,
    lng: 72.784445,
    details:
      "Umra Food Park, Sri Nehru Nagar Society, Umra Gam, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "153R", destination: "Kapodara" },
    ],
  },
  {
    name: "Umra Gaam",
    lat: 21.171606,
    lng: 72.782144,
    details:
      "Umra Gaam, Raghuvir Society, Sri Nehru Nagar Society, Umra Gam, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "14", destination: "ONGC Colony" },
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "14", destination: "Kosad EWS H2" },
      { bus_number: "153R", destination: "Kapodara" },
    ],
  },
  {
    name: "Umra Health Centre",
    lat: 21.171954,
    lng: 72.779687,
    details:
      "Umra Health Centre, Umra Gam, Athwa, Rundh, Surat, Gujarat 395007, India",
    timetable: [{ bus_number: "153R", destination: "Kapodara" }],
  },
  {
    name: "Parle Point",
    lat: 21.175053,
    lng: 72.794619,
    details: "Parle Point, Umra Gam, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "706", destination: "Iskcon Cirle" },
      { bus_number: "206", destination: "C.K. Pithawala Eng. College" },
      { bus_number: "206", destination: "Chowk" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "136", destination: "Surat Terminal" },
      { bus_number: "706", destination: "V.N.S.G. University" },
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "153R", destination: "Kapodara" },
    ],
  },
  {
    name: "V.T Choksi College",
    lat: 21.17657,
    lng: 72.796679,
    details:
      "V.T Choksi College, Meghdoot Society, Athwalines, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "216K", destination: "Chowk" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "706", destination: "V.N.S.G. University" },
      { bus_number: "153R", destination: "Kapodara" },
      { bus_number: "706", destination: "Iskcon Circle" },
      { bus_number: "216B", destination: "Bhimpore" },
    ],
  },
  {
    name: "Gujarati School Ghod DoD Road",
    lat: 21.174415,
    lng: 72.798465,
    details:
      "Gujarati School Ghod DoD Road, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "106S", destination: "Railway Station Terminal" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "126R", destination: "Someshwar Junction" },
    ],
  },
  {
    name: "Tribhuvan Complex Ghod DoD Road",
    lat: 21.1748,
    lng: 72.801528,
    details:
      "Tribhuvan Complex Ghod DoD Road, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "106S", destination: "Railway Station Terminal" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "126R", destination: "Someshwar Junction" },
    ],
  },
  {
    name: "Rangeela Park Ghod DoD Road",
    lat: 21.175054,
    lng: 72.804849,
    details: "Rangeela Park Ghod DoD Road, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "106S", destination: "Railway Station Terminal" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "126R", destination: "Someshwar Junction" },
    ],
  },
  {
    name: "Athwa Pumping Station",
    lat: 21.177914,
    lng: 72.804426,
    details:
      "Athwa Pumping Station, Arogya Nagar, Athwa, Surat, Gujarat 395001, India",
    timetable: [],
  },
  {
    name: "Mira Nagar Society",
    lat: 21.174575,
    lng: 72.811234,
    details:
      "Mira Nagar Society, Ram Chowk, Subhash Nagar, Athwa, Surat, Gujarat 395008, India",
    timetable: [],
  },
  {
    name: "Adarsh Society",
    lat: 21.177849,
    lng: 72.811546,
    details: "Adarsh Society, Athwa, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "106R", destination: "Railway Station Terminal" },
      { bus_number: "106S", destination: "Railway Station Terminal" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      {
        bus_number: "106S",
        destination: "Abhva Gaam(Saraswati Mahavidhyalay)",
      },
    ],
  },
  {
    name: "St.Xavier's High School Ghod DoD Road",
    lat: 21.175717,
    lng: 72.810182,
    details:
      "St.Xavier's High School Ghod DoD Road, Miranagar Society, Athwa, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "106R", destination: "Railway Station Terminal" },
      { bus_number: "716", destination: "Gail India Ltd VIP Road" },
      {
        bus_number: "106S",
        destination: "Abhva Gaam(Saraswati Mahavidhyalay)",
      },
      { bus_number: "716", destination: "Sai Pujan Residency" },
      { bus_number: "126R", destination: "Someshwar Junction" },
    ],
  },
  {
    name: "Panjara Pol Ghod DoD Road",
    lat: 21.176267,
    lng: 72.81609,
    details:
      "Panjara Pol Ghod DoD Road, IOC Colony, Subhash Nagar, Athwa, Surat, Gujarat 395017, India",
    timetable: [
      { bus_number: "126R", destination: "Someshwar Junction" },
      { bus_number: "126R", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Income Tax",
    lat: 21.175848,
    lng: 72.819244,
    details: "Income Tax, Khatodra Wadi, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "205K", destination: "Chowk" },
      { bus_number: "205K", destination: "Lajpore Jail" },
      { bus_number: "116R", destination: "Khajod Gam" },
      { bus_number: "116R", destination: "Railway Station Terminal" },
      { bus_number: "205G", destination: "Gabheni Terminal" },
      { bus_number: "116BR", destination: "Khajod Gam (Via Bhimrad Gaam)" },
    ],
  },
  {
    name: "Khatodara Wadi",
    lat: 21.178197,
    lng: 72.825199,
    details: "Khatodara Wadi, Khatodra Wadi, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "105", destination: "Railway Station Terminal" },
      { bus_number: "105", destination: "Chiku Wadi" },
    ],
  },
  {
    name: "Galaxy Enclave",
    lat: 21.190046,
    lng: 72.774949,
    details: "Galaxy Enclave, Pal Gam, Surat, Gujarat 394510, India",
    timetable: [
      { bus_number: "147J", destination: "Green City Bhatha" },
      { bus_number: "147J", destination: "Lambe Hanuman Temple" },
    ],
  },
  {
    name: "Green City",
    lat: 21.18976,
    lng: 72.770753,
    details: "Green City, Surat, Gujarat 394510, India",
    timetable: [
      { bus_number: "147J", destination: "Green City Bhatha" },
      { bus_number: "147J", destination: "Lambe Hanuman Temple" },
    ],
  },
  {
    name: "Green City Bhatha Approach",
    lat: 21.18844,
    lng: 72.767818,
    details: "Green City Bhatha Approach, Bhatha, Surat, Gujarat 394510, India",
    timetable: [
      { bus_number: "147J", destination: "Green City Bhatha" },
      { bus_number: "147J", destination: "Lambe Hanuman Temple" },
    ],
  },
  {
    name: "Green City Bhatha",
    lat: 21.188631,
    lng: 72.765808,
    details: "Green City Bhatha, Bhatha, Surat, Gujarat 394510, India",
    timetable: [{ bus_number: "147J", destination: "Lambe Hanuman Temple" }],
  },
  {
    name: "Bhatha Gaam",
    lat: 21.184328,
    lng: 72.761888,
    details: "Bhatha Gaam, Bhatha, Surat, Gujarat 394510, India",
    timetable: [
      { bus_number: "658", destination: "Mora Char Rasta" },
      { bus_number: "658", destination: "Adajan GSRTC" },
    ],
  },
  {
    name: "ONGC Road Junction",
    lat: 21.190507,
    lng: 72.722742,
    details: "ONGC Road Junction, Ichchhapor, Gujarat 394515, India",
    timetable: [{ bus_number: "658", destination: "Adajan GSRTC" }],
  },
  {
    name: "Icchapor Town",
    lat: 21.191301,
    lng: 72.72805,
    details: "Icchapor Town, Ichchhapor, Gujarat 394510, India",
    timetable: [
      { bus_number: "658", destination: "Mora Char Rasta" },
      { bus_number: "658", destination: "Adajan GSRTC" },
    ],
  },
  {
    name: "Hotel Excellency Icchapor",
    lat: 21.19156,
    lng: 72.731091,
    details: "Hotel Excellency Icchapor, Ichchhapor, Gujarat 394510, India",
    timetable: [
      { bus_number: "658", destination: "Mora Char Rasta" },
      { bus_number: "658", destination: "Adajan GSRTC" },
    ],
  },
  {
    name: "Rupali Junction BRTS",
    lat: 21.170972,
    lng: 72.816412,
    details:
      "Rupali Junction BRTS, Janta Nagar, Navrachna Society, Bhatar, Athwa, Surat, Gujarat 395017, India",
    timetable: [
      { bus_number: "12", destination: "Sarthana Nature Park BRTS" },
      { bus_number: "15CC", destination: "Althan Depot/Terminal" },
      { bus_number: "12", destination: "ONGC Colony" },
      { bus_number: "116R", destination: "Railway Station Terminal" },
      { bus_number: "116R", destination: "Khajod Gam" },
      { bus_number: "15AA", destination: "Althan Depot/Terminal" },
    ],
  },
  {
    name: "Jamna Nagar Junction BRTS",
    lat: 21.16958,
    lng: 72.810913,
    details:
      "Jamna Nagar Junction BRTS, Jeevkar Nagar, Athwa, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "15AA", destination: "Althan Depot/Terminal" },
      { bus_number: "15CC", destination: "Althan Depot/Terminal" },
      { bus_number: "12", destination: "ONGC Colony" },
      { bus_number: "12", destination: "Sarthana Nature Park BRTS" },
    ],
  },
  {
    name: "Trimurti Apartment",
    lat: 21.170113,
    lng: 72.811664,
    details:
      "Trimurti Apartment, Subhash Nagar, Athwa, Surat, Gujarat 395008, India",
    timetable: [],
  },
  {
    name: "Vivekanand Garden",
    lat: 21.169161,
    lng: 72.811787,
    details:
      "Vivekanand Garden, Poonam Nagar, Bhatar, Athwa, Surat, Gujarat 395017, India",
    timetable: [],
  },
  {
    name: "Fruit Market",
    lat: 21.167021,
    lng: 72.814058,
    details: "Fruit Market, Bhatar, Athwa, Surat, Gujarat 395017, India",
    timetable: [],
  },
  {
    name: "Uma Bhavan Bhatar Road",
    lat: 21.167728,
    lng: 72.814428,
    details:
      "Uma Bhavan Bhatar Road, Bhatar, Athwa, Surat, Gujarat 395017, India",
    timetable: [
      { bus_number: "116R", destination: "Khajod Gam" },
      { bus_number: "116BR", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Rupali Canal Junction Bhatar Road",
    lat: 21.16984,
    lng: 72.815427,
    details:
      "Rupali Canal Junction Bhatar Road, Bhatar, Athwa, Surat, Gujarat 395017, India",
    timetable: [
      { bus_number: "116BR", destination: "Khajod Gam (Via Bhimrad Gaam)" },
      { bus_number: "116BR", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Sosyo Circle Udhana Magdalla Road",
    lat: 21.171977,
    lng: 72.826363,
    details:
      "Sosyo Circle Udhana Magdalla Road, Gandhi Kutir, Surat, Gujarat 395017, India",
    timetable: [
      { bus_number: "506", destination: "Sunrise Vidyalay Dindoli" },
      { bus_number: "146", destination: "Railway Station Terminal" },
      { bus_number: "506D", destination: "Vesu Gaam" },
      { bus_number: "146", destination: "Gail India Ltd VIP Road" },
    ],
  },
  {
    name: "Sosyo Circle",
    lat: 21.171036,
    lng: 72.826953,
    details: "Sosyo Circle, Laxmi Nagar, Udhana, Surat, Gujarat 395017, India",
    timetable: [
      { bus_number: "105", destination: "Railway Station Terminal" },
      { bus_number: "205K", destination: "Chowk" },
      { bus_number: "205G", destination: "Chowk" },
      { bus_number: "105", destination: "Chiku Wadi" },
      { bus_number: "205K", destination: "Lajpore Jail" },
    ],
  },
  {
    name: "Khatodara Water Works",
    lat: 21.174258,
    lng: 72.829131,
    details:
      "Khatodara Water Works, Laxmi Nagar, Udhana, Surat, Gujarat 395017, India",
    timetable: [
      { bus_number: "506D", destination: "Vesu Gaam" },
      { bus_number: "146", destination: "Railway Station Terminal" },
      { bus_number: "146", destination: "Gail India Ltd VIP Road" },
      { bus_number: "506", destination: "Sunrise Vidyalay Dindoli" },
    ],
  },
  {
    name: "Khatodara GIDC",
    lat: 21.175308,
    lng: 72.826492,
    details: "Khatodara GIDC, Khatodra Wadi, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "105", destination: "Railway Station Terminal" },
      { bus_number: "105", destination: "Chiku Wadi" },
    ],
  },
  {
    name: "Udhna Darvaja",
    lat: 21.183411,
    lng: 72.830622,
    details:
      "Udhna Darvaja, Maan Darwaja, Khatodra Wadi, Surat, Gujarat 395008, India",
    timetable: [],
  },
  {
    name: "Maan Darwaja",
    lat: 21.183651,
    lng: 72.833025,
    details:
      "Maan Darwaja, Maan Darwaja, Aman Nagar, Surat, Gujarat 395008, India",
    timetable: [
      { bus_number: "105", destination: "Railway Station Terminal" },
      { bus_number: "106S", destination: "Railway Station Terminal" },
      { bus_number: "146", destination: "Gail India Ltd VIP Road" },
      { bus_number: "204", destination: "Chowk" },
      { bus_number: "105", destination: "Chiku Wadi" },
      { bus_number: "01", destination: "Udhna Darwaza" },
      { bus_number: "117", destination: "Railway Station Terminal" },
      { bus_number: "153R", destination: "Kapodara" },
      { bus_number: "209J", destination: "Dr S.P. Mukher Brid" },
      { bus_number: "209J", destination: "Vrukshlaxmi Society" },
      { bus_number: "116R", destination: "Khajod Gam" },
      { bus_number: "106R", destination: "Abhva Gam" },
      { bus_number: "02", destination: "Kinnary Cinema" },
      { bus_number: "117", destination: "Suman Jyot EWS" },
      { bus_number: "126R", destination: "Someshwar Junction" },
    ],
  },
  {
    name: "Kinnary Cinema",
    lat: 21.185512,
    lng: 72.836802,
    details:
      "Kinnary Cinema, Maan Darwaja, Aanjada Nagar, Aman Nagar, Surat, Gujarat 395008, India",
    timetable: [
      { bus_number: "209J", destination: "Dr S.P. Mukher Brid" },
      { bus_number: "116R", destination: "Khajod Gam" },
      { bus_number: "117", destination: "Suman Jyot EWS" },
      { bus_number: "106R", destination: "Abhva Gam" },
      { bus_number: "209J", destination: "Vrukshlaxmi Society" },
      { bus_number: "02", destination: "Kamela Darwaja" },
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "146", destination: "Railway Station Terminal" },
      { bus_number: "126R", destination: "Someshwar Junction" },
      { bus_number: "105", destination: "Chiku Wadi" },
      { bus_number: "204", destination: "Raj Empire Gadodara" },
      { bus_number: "01", destination: "Maan Darwaza" },
      { bus_number: "117", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Janta Hospital",
    lat: 21.186753,
    lng: 72.827919,
    details: "Janta Hospital, Sagrampura, Surat, Gujarat 395008, India",
    timetable: [
      { bus_number: "302V", destination: "Moti Ved" },
      { bus_number: "209J", destination: "Vrukshlaxmi Society" },
      { bus_number: "209J", destination: "Dr S.P. Mukher Brid" },
      { bus_number: "302", destination: "Dabholi Gaam Approach" },
      { bus_number: "302", destination: "Kharwarnagar BRTS" },
    ],
  },
  {
    name: "S.M.C. Water Department",
    lat: 21.188813,
    lng: 72.824399,
    details: "S.M.C. Water Department, Rudrapura, Surat, Gujarat 395001, India",
    timetable: [
      { bus_number: "209J", destination: "Vrukshlaxmi Society" },
      { bus_number: "209J", destination: "Dr S.P. Mukher Brid" },
    ],
  },
  {
    name: "Navsari Bazar",
    lat: 21.189013,
    lng: 72.826653,
    details: "Navsari Bazar, Rustampura, Surat, Gujarat 395008, India",
    timetable: [
      { bus_number: "209J", destination: "Vrukshlaxmi Society" },
      { bus_number: "209J", destination: "Dr S.P. Mukher Brid" },
      { bus_number: "302", destination: "Kharwarnagar BRTS" },
      { bus_number: "302", destination: "Dabholi Gaam Approach" },
      { bus_number: "302V", destination: "Kharwarnagar BRTS" },
    ],
  },
  {
    name: "Gopi Talav Market",
    lat: 21.190094,
    lng: 72.827747,
    details: "Gopi Talav Market, Rustampura, Surat, Gujarat 395008, India",
    timetable: [
      { bus_number: "209J", destination: "Vrukshlaxmi Society" },
      { bus_number: "209J", destination: "Dr S.P. Mukher Brid" },
      { bus_number: "302", destination: "Kharwarnagar BRTS" },
      { bus_number: "302", destination: "Dabholi Gaam Approach" },
      { bus_number: "302V", destination: "Kharwarnagar BRTS" },
    ],
  },
  {
    name: "Halpati Colony",
    lat: 21.183912,
    lng: 72.838991,
    details: "Halpati Colony, Nehru Nagar, Surat, Gujarat 395008, India",
    timetable: [
      { bus_number: "209J", destination: "Dr S.P. Mukher Brid" },
      { bus_number: "104", destination: "Vrukshlaxmi Society" },
      { bus_number: "104", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Sahara Darwaja",
    lat: 21.194515,
    lng: 72.84457,
    details:
      "Sahara Darwaja, Sahara Darwaja, New Textile Market, Surat, Gujarat 395101, India",
    timetable: [],
  },
  {
    name: "Sai Darshan Market",
    lat: 21.187433,
    lng: 72.843068,
    details:
      "Sai Darshan Market, Sahara Darwaja, Moti Begumwadi, New Textile Market, Surat, Gujarat 395002, India",
    timetable: [
      { bus_number: "204", destination: "Chowk" },
      { bus_number: "204", destination: "Raj Empire Gadodara" },
      { bus_number: "254", destination: "Suman Darshan" },
      { bus_number: "254", destination: "Mangal Pandey Hall Gadodara" },
    ],
  },
  {
    name: "Linear Bus Stop",
    lat: 21.202463,
    lng: 72.839463,
    details:
      "Linear Bus Stop, Ring Rd, Railway Station Area, Varachha, Surat, Gujarat 395003, India",
    timetable: [
      { bus_number: "19", destination: "Vareli Gaam" },
      { bus_number: "254", destination: "Suman Darshan" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "23", destination: "Sachin Railway Station" },
      { bus_number: "21", destination: "Althan Depot/Terminal" },
      { bus_number: "23", destination: "Kamrej Terminal" },
      { bus_number: "20", destination: "Kosad EWS H2" },
      { bus_number: "117", destination: "Railway Station Terminal" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "104", destination: "Railway Station Terminal" },
      { bus_number: "116BR", destination: "Khajod Gam (Via Bhimrad Gaam)" },
      { bus_number: "105", destination: "Railway Station Terminal" },
      { bus_number: "104", destination: "Vrukshlaxmi Society" },
      { bus_number: "126R", destination: "Railway Station Terminal" },
      { bus_number: "153R", destination: "Kapodara" },
      { bus_number: "02", destination: "Railway Station Terminal" },
      { bus_number: "21", destination: "Jahangirpura Community Hall" },
    ],
  },
  {
    name: "Delhi Gate Surat",
    lat: 21.203357,
    lng: 72.83995,
    details:
      "Delhi Gate Surat, Railway Station Area, Varachha, Surat, Gujarat 395008, India",
    timetable: [],
  },
  {
    name: "Lambe Hanuman Temple",
    lat: 21.204349,
    lng: 72.842798,
    details:
      "Lambe Hanuman Temple, Saify Society, Varachha, Surat, Gujarat 395008, India",
    timetable: [
      { bus_number: "147J", destination: "Green City Bhatha" },
      { bus_number: "402", destination: "Magob Gam" },
      { bus_number: "402", destination: "Utran Railway Station" },
      { bus_number: "103K", destination: "Kathor Gaam" },
      { bus_number: "103V", destination: "Ramvatika Society" },
      { bus_number: "103S", destination: "Haridarshan Residency" },
    ],
  },
  {
    name: "Tekrawala School",
    lat: 21.209249,
    lng: 72.793275,
    details:
      "Tekrawala School, Pushpak Society, Adajan, Surat, Gujarat 395009, India",
    timetable: [],
  },
  {
    name: "bsnl Office",
    lat: 21.208144,
    lng: 72.789279,
    details:
      "bsnl Office, Kedarnath Society, Mahadev Nagar, Pankaj Nagar, Surat, Gujarat 395009, India",
    timetable: [
      { bus_number: "117", destination: "Railway Station Terminal" },
      { bus_number: "117P", destination: "Railway Station Terminal" },
      { bus_number: "117", destination: "Suman Jyot EWS" },
    ],
  },
  {
    name: "Vichar Kranti Circle",
    lat: 21.21122,
    lng: 72.790378,
    details:
      "Vichar Kranti Circle, New Mahalaxmi Society, Adajan, Surat, Gujarat 395009, India",
    timetable: [],
  },
  {
    name: "Bhagyodaya Society",
    lat: 21.211105,
    lng: 72.788356,
    details:
      "Bhagyodaya Society, Dindayal Society, Palanpur Patia, Surat, Gujarat 395005, India",
    timetable: [
      { bus_number: "716", destination: "Sai Pujan Residency" },
      { bus_number: "117", destination: "Railway Station Terminal" },
      { bus_number: "117P", destination: "Railway Station Terminal" },
      { bus_number: "716", destination: "Gail India Ltd VIP Road" },
    ],
  },
  {
    name: "Palanpur Patiya Circle",
    lat: 21.21147,
    lng: 72.790083,
    details:
      "Palanpur Patiya Circle, Dindayal Society, Palanpur Patia, Surat, Gujarat 395005, India",
    timetable: [],
  },
  {
    name: "Housing Board Palanpur",
    lat: 21.21307,
    lng: 72.787868,
    details:
      "Housing Board Palanpur, Dindayal Society, Palanpur Patia, Surat, Gujarat 395005, India",
    timetable: [],
  },
  {
    name: "Ramnagar BRTS",
    lat: 21.2162,
    lng: 72.791422,
    details:
      "Ramnagar BRTS, NH228, Ramnagar, Sima Nagar, Surat, Gujarat 395009, India",
    timetable: [
      {
        bus_number: "137J",
        destination: "Kavi Shree Amrut Ghayal School Variav",
      },
      { bus_number: "14", destination: "ONGC Colony" },
      { bus_number: "137J", destination: "Railway Station Terminal" },
      { bus_number: "21", destination: "Jahangirpura Community Hall" },
      { bus_number: "21", destination: "Althan Depot/Terminal" },
      { bus_number: "14", destination: "Kosad EWS H2" },
      { bus_number: "217M", destination: "Bhesan Gaam" },
      { bus_number: "207E", destination: "Chowk" },
    ],
  },
  {
    name: "Ram Nagar",
    lat: 21.217361,
    lng: 72.787321,
    details: "Ram Nagar, Ramnagar, Sima Nagar, Surat, Gujarat 395005, India",
    timetable: [
      { bus_number: "706", destination: "V.N.S.G. University" },
      { bus_number: "706", destination: "Iskcon Circle" },
    ],
  },
  {
    name: "Anand Nagar Society",
    lat: 21.219961,
    lng: 72.787213,
    details:
      "Anand Nagar Society, Anand Nagar Society, Morabhagal, Surat, Gujarat 395005, India",
    timetable: [],
  },
  {
    name: "Gayatri Mandir",
    lat: 21.222401,
    lng: 72.787278,
    details:
      "Gayatri Mandir, Dattatrey Society, Morabhagal, Surat, Gujarat 395005, India",
    timetable: [
      { bus_number: "716", destination: "Gail India Ltd VIP Road" },
      { bus_number: "706", destination: "V.N.S.G. University" },
      { bus_number: "706", destination: "Iskcon Circle" },
      { bus_number: "217M", destination: "Bhesan Gaam" },
      { bus_number: "716", destination: "Sai Pujan Residency" },
      { bus_number: "217M", destination: "Makkai Pool U" },
    ],
  },
  {
    name: "Devashish Nagar Mora Bhagal",
    lat: 21.221881,
    lng: 72.785218,
    details:
      "Devashish Nagar Mora Bhagal, Devashish Nagar, Morabhagal, Surat, Gujarat 395005, India",
    timetable: [],
  },
  {
    name: "Shreenathaji Haveli Ramnagar",
    lat: 21.219121,
    lng: 72.785089,
    details:
      "Shreenathaji Haveli Ramnagar, Gopinath Society, Ramnagar, Sima Nagar, Surat, Gujarat 395005, India",
    timetable: [],
  },
  {
    name: "Raj Harmony",
    lat: 21.221461,
    lng: 72.777965,
    details: "Raj Harmony, Surat, Gujarat 395005, India",
    timetable: [
      { bus_number: "107J", destination: "Railway Station Terminal" },
      { bus_number: "107J", destination: "Vivekanand College" },
      { bus_number: "217M", destination: "Makkai Pool U" },
      { bus_number: "217", destination: "Makkai Pool U" },
    ],
  },
  {
    name: "Anand Villa",
    lat: 21.220881,
    lng: 72.774146,
    details:
      "Anand Villa, Prabhudarshan Society, Dahin Nagar, Surat, Gujarat 395005, India",
    timetable: [
      { bus_number: "217M", destination: "Makkai Pool U" },
      { bus_number: "217", destination: "Makkai Pool U" },
      { bus_number: "217M", destination: "Bhesan Gaam" },
      { bus_number: "217", destination: "Bhesan Gaam" },
    ],
  },
  {
    name: "SMC Staff Quarters",
    lat: 21.218381,
    lng: 72.777879,
    details:
      "SMC Staff Quarters, Jahangirabad, Sima Nagar, Surat, Gujarat 395005, India",
    timetable: [],
  },
  {
    name: "Tapash Nagar",
    lat: 21.21514,
    lng: 72.777514,
    details:
      "Tapash Nagar, Prashant Nagar, Jahangirabad, Sima Nagar, Surat, Gujarat 395009, India",
    timetable: [],
  },
  {
    name: "SMC Ward Office",
    lat: 21.211865,
    lng: 72.77715,
    details:
      "SMC Ward Office, Prashant Nagar, Jahangirabad, Palanpur Jakatnaka, Surat, Gujarat 395009, India",
    timetable: [],
  },
  {
    name: "Kargil Chowk BRTS",
    lat: 21.165123,
    lng: 72.780411,
    details:
      "Kargil Chowk BRTS, SVNIT Campus, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "14", destination: "ONGC Colony" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "14", destination: "Kosad EWS H2" },
      { bus_number: "106R", destination: "Railway Station Terminal" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "226J", destination: "V.N.S.G. University" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "206", destination: "Chowk" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "216B", destination: "Chwk" },
    ],
  },
  {
    name: "S.V.N.I.T. BRTS",
    lat: 21.167374,
    lng: 72.784081,
    details:
      "S.V.N.I.T. BRTS, SVNIT Campus, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "106R", destination: "Railway Station Terminal" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "14", destination: "Kosad EWS H2" },
      { bus_number: "206", destination: "Chowk" },
      { bus_number: "14", destination: "ONGC Colony" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "226J", destination: "V.N.S.G. University" },
      { bus_number: "216B", destination: "Chowk" },
      { bus_number: "206", destination: "C.K. Pithawala Eng. College U" },
    ],
  },
  {
    name: "Icchanath Mahadev Temple",
    lat: 21.168145,
    lng: 72.786269,
    details:
      "Icchanath Mahadev Temple, SVNIT Campus, Athwa, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "153R", destination: "Umra Health Centre" },
      { bus_number: "106R", destination: "Railway Station Terminal" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "216K", destination: "Chowk" },
      { bus_number: "216B", destination: "Bhimpore" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "226J", destination: "V.N.S.G. University" },
      { bus_number: "153R", destination: "Kapodara" },
      { bus_number: "216K", destination: "Dumas Langar" },
    ],
  },
  {
    name: "Lancers Army School BRTS",
    lat: 21.15949,
    lng: 72.770991,
    details:
      "Lancers Army School BRTS, Piplod, Rundh, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "14", destination: "Kosad EWS H2" },
      { bus_number: "106R", destination: "Railway Station Terminal" },
      { bus_number: "226J", destination: "Kosad Gam" },
      { bus_number: "206", destination: "Chowk" },
      { bus_number: "14", destination: "ONGC Colony" },
      { bus_number: "226J", destination: "V.N.S.G. University" },
      { bus_number: "216B", destination: "Chowk" },
      { bus_number: "206", destination: "C.K. Pithawala Eng. College U" },
    ],
  },
  {
    name: "Piplod BRTS",
    lat: 21.161431,
    lng: 72.774639,
    details: "Piplod BRTS, Piplod, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "14", destination: "Kosad EWS H2" },
      { bus_number: "14", destination: "ONGC Colony" },
      { bus_number: "216B", destination: "Chowk" },
      { bus_number: "106R", destination: "Railway Station Terminal" },
      { bus_number: "206", destination: "C.K. Pithawala Eng. College U" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "206", destination: "Chowk" },
    ],
  },
  {
    name: "Goverdhan Nathji Haveli BRTS",
    lat: 21.155978,
    lng: 72.765734,
    details:
      "Goverdhan Nathji Haveli BRTS, Piplod, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "14", destination: "Kosad EWS H2" },
      { bus_number: "14", destination: "ONGC Colony" },
      { bus_number: "216K", destination: "Chowk" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "206", destination: "C.K. Pithawala Eng. College U" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "206", destination: "Chowk" },
      { bus_number: "216B", destination: "Bhimpore" },
    ],
  },
  {
    name: "Bharti Maiya School",
    lat: 21.155178,
    lng: 72.771657,
    details: "Bharti Maiya School, Piplod, Surat, Gujarat 395007, India",
    timetable: [
      { bus_number: "106R", destination: "Abhva Gaam" },
      { bus_number: "106R", destination: "Railway Station Terminal" },
    ],
  },
  {
    name: "Magdalla Gam BRTS",
    lat: 21.14213,
    lng: 72.755585,
    details:
      "Magdalla Gam BRTS, Gail Colony, Vesu, Surat, Gujarat 394518, India",
    timetable: [
      { bus_number: "12", destination: "ONGC Colony" },
      { bus_number: "14", destination: "Kosad EWS H2" },
      { bus_number: "12", destination: "Sarthana Nature Park BRTS" },
      { bus_number: "216K", destination: "Dumas Langar" },
      { bus_number: "136", destination: "Railway Station Terminal" },
      { bus_number: "136", destination: "Surat Airport" },
      { bus_number: "206", destination: "Chowk" },
    ],
  },
];
